// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks -source=service.go
//
// Package mocks is a generated GoMock package.
package mocks

import (
	config "project-helper/internal/config"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConfigService is a mock of ConfigService interface.
type MockConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockConfigServiceMockRecorder
}

// MockConfigServiceMockRecorder is the mock recorder for MockConfigService.
type MockConfigServiceMockRecorder struct {
	mock *MockConfigService
}

// NewMockConfigService creates a new mock instance.
func NewMockConfigService(ctrl *gomock.Controller) *MockConfigService {
	mock := &MockConfigService{ctrl: ctrl}
	mock.recorder = &MockConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigService) EXPECT() *MockConfigServiceMockRecorder {
	return m.recorder
}

// GetPredefinedArgs mocks base method.
func (m *MockConfigService) GetPredefinedArgs() map[string]config.PredefinedArg {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPredefinedArgValues")
	ret0, _ := ret[0].(map[string]config.PredefinedArg)
	return ret0
}

// GetPredefinedArgs indicates an expected call of GetPredefinedArgs.
func (mr *MockConfigServiceMockRecorder) GetPredefinedArgs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPredefinedArgValues", reflect.TypeOf((*MockConfigService)(nil).GetPredefinedArgs))
}
